### ISSUE TITLE
Correct MEASUREMENT_COLOR in write_config.py

### ISSUE THREAD

**Issue by r3m0chop** [chop-dbhi/studycentric#18]
Currently looking for environment var `MEAUREMENT_COLOR` rather than `MEASUREMENT_COLOR` at:  https://github.com/chop-dbhi/studycentric/blob/master/scripts/write_config.py#L29

**Comment by jeffmax** [comment]
@r3m0chop thanks, nice catch. Are you using this for the project? Do you have write access to this repo?

**Comment by r3m0chop** [comment]
Thanks @jeffmax.  

Nope, not using this variable at this time.  Just happened to notice it within the file (and its corresponding description in the https://github.com/chop-dbhi/studycentric/blob/master/README.md) while browsing the code, and thought I'd mention it before I forgot.  

I do not yet have any write access to this repo, but am not yet in need of any other changes to push, either).  Regarding this particular issue,  I am not sure how many active users there are of this variable as it is currently expected, so I would want to be careful to not break any existing systems (at least, not without further communicating any such change).

**Comment by r3m0chop** [comment]
Cool, @jeffmax - you may want to update the README.md to match your fix as well, thanks!

**Comment by jeffmax** [comment]
@r3m0chop done, thanks.
